INSERT INTO CONE(NAME) VALUES ('waffle cone');
INSERT INTO CONE(NAME) VALUES ('chocolate-dipped cone');
INSERT INTO CONE(NAME) VALUES ('sugar cone');
INSERT INTO CONE(NAME) VALUES ('waffle bowl');
INSERT INTO CONE(NAME) VALUES ('pretzel cone');

INSERT INTO FLAVOR(NAME) VALUES ('vanilla');
INSERT INTO FLAVOR(NAME) VALUES ('chocolate');
INSERT INTO FLAVOR(NAME) VALUES ('strawberry');
INSERT INTO FLAVOR(NAME) VALUES ('banana');
INSERT INTO FLAVOR(NAME) VALUES ('fudge');
INSERT INTO FLAVOR(NAME) VALUES ('coconut');

INSERT INTO TOPPING(NAME) VALUES ('chocolate chips');
INSERT INTO TOPPING(NAME) VALUES ('chocolate sprinkles');
INSERT INTO TOPPING(NAME) VALUES ('whipped cream');
INSERT INTO TOPPING(NAME) VALUES ('mini candy cane');
INSERT INTO TOPPING(NAME) VALUES ('powdered sugar');
INSERT INTO TOPPING(NAME) VALUES ('melted fudge');
INSERT INTO TOPPING(NAME) VALUES ('melted chocolate');

INSERT INTO PRODUCT(NAME, CONE, FLAVOR) VALUES ('Fudge Sundae', 4, 2);
INSERT INTO PRODUCT(NAME, CONE, FLAVOR) VALUES ('Chocolate Dream', 2, 2);
INSERT INTO PRODUCT(NAME, CONE, FLAVOR) VALUES ('Banana Republic', 3, 4);
INSERT INTO PRODUCT(NAME, CONE, FLAVOR) VALUES ('Strawberry Cloud', 5, 3);

INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (1, 6);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (1, 4);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (2, 1);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (2, 3);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (2, 4);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (3, 7);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (3, 4);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (4, 1);
INSERT INTO PRODUCT_TOPPINGS(PRODUCT_ID, TOPPING_ID) VALUES (4, 5);