CREATE TABLE CONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE FLAVOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE TOPPING (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    CONE INT NOT NULL,
    FLAVOR INT NOT NULL,
    FOREIGN KEY(CONE) REFERENCES CONE,
    FOREIGN KEY(FLAVOR) REFERENCES FLAVOR
);

CREATE TABLE PRODUCT_TOPPINGS (
    PRODUCT_ID INT NOT NULL,
    TOPPING_ID INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT ON DELETE CASCADE,
    FOREIGN KEY (TOPPING_ID) REFERENCES TOPPING ON DELETE CASCADE
);
